name: Spring Boot

on:
  push:
    branches:
      - main
      - master

jobs:
  run-unit-tests:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@main
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: 3.8.2

      - name: Unit Tests
        run: mvn clean package

      - name: Rename the artifact
        run: cp target/kradadtod-api-0.0.1-SNAPSHOT.jar kradadtod-backend.jar

      - name: Save the artifact
        uses: actions/upload-artifact@master
        with:
          name: kradadtod-backend
          path: kradadtod-backend.jar

  fake-deploy:
    runs-on: self-hosted
    needs: run-unit-tests
    steps:
      - name: Get the artifact
        uses: actions/download-artifact@master
        with:
          name: kradadtod-backend

      - name: Fake deploy
        run: ls kradadtod-backend-*.jar

      - name: Go to directory
        run: cd /home/ubuntu/sites/development.akkharawit.com/actions-runner/_work/kradadtod-api/kradadtod-api

      - name: Deploy
        run: pm2 restart kradadtod-api --watch || pm2 start java -jar kradadtod-backend.jar --name kradadtod-api --watch
